### ISSUE TITLE
RD : Documentation storage

### ISSUE THREAD

**Issue by jheussler** [objective-php/documentation#3]
Find a way to store the documentation (as file, in a dabatase, whatever, to define)

**Comment by louis-cuny** [comment]
For the api-doc generated from the phpdoc : html files are outputed and they just have to be at the good place in the web app project. 

For the user-guide doc : We may write markdown files with a significative hierarchy. Versioned in a github repository. 
We will need a tool to show nicely the markdown doc.
We will need a tool to write fastly the markdown files. No priority

**Comment by louis-cuny** [comment]
Free markdown rendering tools : 
- Docusaurus
- Docsify

**Comment by louis-cuny** [comment]
For the md files linked to specific objective-php component with a specific version. Why not just let them in the corresponding repositories. Sami can easily catch them. 

This proposal would be great in 2 points : 
- The md files will inevitably be versioned correnspending to the versions of the component.
- The md files will complete the basic README.md and be directly found for the users who found the github repository

Not sure if it is an issue, but we would like to separate the md doc from the genrated one. We will have to remanipulate the md files from where we will let them after sami's work

The more general getting started doc can be stored in a new repository or why not, directly in this repository

**Comment by louis-cuny** [comment]
I made a Json and used a JsonMapper to keep the informations on the packages and versions that as been generated
