### ISSUE TITLE
DEV : Hook / Update

### ISSUE THREAD

**Issue by jheussler** [objective-php/documentation#5]
Write the hook we will replicate on each objective-php's repo on a tag to make a new version of the documentation.
We will need an update script on our website who pull the new data and generate the data doc with it.

**Comment by louis-cuny** [comment]
github doesn't have a post-tagging hook, they have a post-new-release hook. We will have to verify if every release will trigger the hook. In a strange way, the get-releases http request doesn't return all releases. Only "big ones" Ex: v1.0 and v1.0.1 on objective-php/primitives and not all the following releases.

**Comment by louis-cuny** [comment]
In the repo, add new Webhook: objective-php.org/api/buildapi?version=1.0.0&min-version=2.1
Check for tags
